import { randomInt } from 'node:crypto';

/**
 * Wortliste für erzeugte Passwörter.
 *
 * Kurze, eindeutige, gut tippbare Wörter – ohne Umlaute und ß, weil eine
 * fremde Tastaturbelegung das Anmelden sonst zur Geduldsprobe macht.
 *
 * Eine Wortfolge statt einer Zeichenkette wie `xK9#mQ2!` ist hier die bessere
 * Wahl: Sie lässt sich abschreiben, vorlesen und eintippen, ohne dass man
 * Null und O verwechselt. Sechs Wörter aus 128 ergeben rund 42 Bit; zusammen
 * mit der Sperre nach mehreren Fehlversuchen ist das für eine Anmeldung
 * reichlich.
 */
const WOERTER = [
  'anker',
  'apfel',
  'armband',
  'atlas',
  'auge',
  'bagger',
  'balkon',
  'banane',
  'baum',
  'berg',
  'biene',
  'birne',
  'blatt',
  'blume',
  'boden',
  'bogen',
  'brot',
  'bruecke',
  'buch',
  'buero',
  'busch',
  'dach',
  'damm',
  'decke',
  'delfin',
  'diamant',
  'donner',
  'dorf',
  'drache',
  'druck',
  'duene',
  'eiche',
  'eimer',
  'eisen',
  'elefant',
  'ernte',
  'esel',
  'fahne',
  'faden',
  'falke',
  'feder',
  'fenster',
  'feuer',
  'fisch',
  'flasche',
  'fluss',
  'forelle',
  'frosch',
  'garten',
  'gabel',
  'gipfel',
  'gitarre',
  'glocke',
  'graben',
  'gras',
  'hafen',
  'hammer',
  'hase',
  'haus',
  'heide',
  'hemd',
  'herbst',
  'hirsch',
  'holz',
  'huegel',
  'hund',
  'insel',
  'jacke',
  'kabel',
  'kaefer',
  'kamin',
  'kanal',
  'kerze',
  'kessel',
  'kiesel',
  'kirsche',
  'kissen',
  'kleid',
  'knopf',
  'koffer',
  'krone',
  'kueche',
  'lampe',
  'laub',
  'leiter',
  'licht',
  'lilie',
  'loeffel',
  'luchs',
  'magnet',
  'mantel',
  'markt',
  'mauer',
  'meer',
  'melone',
  'messer',
  'mond',
  'motor',
  'muschel',
  'nadel',
  'nebel',
  'nelke',
  'nest',
  'norden',
  'nuss',
  'ofen',
  'orkan',
  'palme',
  'pappel',
  'pfeil',
  'pflanze',
  'pilz',
  'planet',
  'platz',
  'quelle',
  'rabe',
  'rahmen',
  'regen',
  'riegel',
  'ring',
  'ruder',
  'sattel',
  'schnee',
  'segel',
  'stein',
  'turm',
  'wiese',
  'wolke',
];

/** Erzeugt eine Wortfolge. `randomInt` ist gleichverteilt – `Math.random` nicht. */
export function erzeugePassphrase(anzahlWoerter = 6): string {
  const gewaehlt = Array.from({ length: anzahlWoerter }, () => WOERTER[randomInt(WOERTER.length)]!);
  // Eine zweistellige Zahl am Ende: Manche Formulare anderswo verlangen eine
  // Ziffer, und es kostet nichts.
  return `${gewaehlt.join('-')}-${randomInt(10, 100)}`;
}
